---
# Download Node Exporter file
- name: Download Node Exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v1.10.2/node_exporter-1.10.2.linux-amd64.tar.gz
    dest: /tmp/node_exporter.tar.gz
    mode: '0755'

# Extract it
- name: Extract Node Exporter
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp/
    remote_src: yes

# Move the binary to the right place
- name: Copy Node Exporter binary
  copy:
    src: /tmp/node_exporter-1.10.2.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    mode: '0755'
    remote_src: yes

# Create a user to run the Node Exporter (for security best practice)
- name: Create node_exporter user
  user:
    name: node_exporter
    shell: /bin/false       # Can't log in
    system: yes             # System user
    create_home: no         # No home directory needed

# Create systemd service file
- name: Create systemd service file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  notify: restart node_exporter

# Enable and start the service
- name: Start and enable Node Exporter
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yess