title: Sem02
description: "Server Monitoring Dashboard"
remote_theme: just-the-docs/just-the-docs

url: https://JJotace.github.io/

# ADD THIS LINE - This forces GitHub Pages to use your remote theme
plugins:
  - jekyll-remote-theme

aux_links:
  JIRA Project: https://jjotace.atlassian.net/jira/software/projects/SMD/summary

footer_content: "Juan Cardoso - Sem02 - Technische Berufsschule ZÃ¼rich - Cloud Native Engineering - 2025"